#!/usr/bin/env python3
"""Inline sibling Design Component files so the page works from file://.

`page.dc.html` pulls in `PlatformIcon.dc.html` / `LanguageTag.dc.html`
via <dc-import>. The DC runtime (support.js) resolves those by `fetch()`,
which browsers block on file:// origins ("CORS request not http"). Over
http (GitHub Pages, `just serve`, Claude Design) the fetch works fine.

This regenerates `site/components.js` — a plain <script> (loads on
file://) that pre-populates `window.__resourceBlobs[...]` with each
component's source, the cache the runtime checks before it fetches. So
the .dc.html files stay the single source of truth; this is a derived
build artifact, regenerated by the pre-commit hook and `just build`.

No external deps. Run: python3 scripts/bundle-components.py
"""
import json
import sys
from pathlib import Path

SITE = Path(__file__).resolve().parent.parent / "site"
# Every sibling component except the page itself.
COMPONENTS = sorted(p for p in SITE.glob("*.dc.html") if p.name != "page.dc.html")
OUT = SITE / "components.js"


def main():
    entries = {}
    for path in COMPONENTS:
        # Key must match support.js ensureFetched(): COMPONENT_DIR ("." ) +
        # "/" + encodeURIComponent(name) + ".dc.html".
        key = "./" + path.name
        entries[key] = path.read_text(encoding="utf-8")

    body = json.dumps(entries, ensure_ascii=False, indent=2)
    OUT.write_text(
        "// AUTO-GENERATED by scripts/bundle-components.py — DO NOT EDIT BY HAND.\n"
        "//\n"
        "// Inlines every sibling *.dc.html component (all except page.dc.html) so\n"
        "// <dc-import> resolves without a fetch(), which browsers block on file://\n"
        "// origins. The *.dc.html files are the single source of truth.\n"
        "//\n"
        "// Regenerate whenever a sibling *.dc.html is added / changed / removed:\n"
        "//   - Full repo checkout:  `just build`  (or `python3 scripts/bundle-components.py`).\n"
        "//     The pre-commit hook also does it. See CONTRIBUTING.md.\n"
        "//   - No shell (design tool, flat dir): rebuild this file by hand to match\n"
        "//     this exact shape — IIFE + `var C` map + loop into window.__resourceBlobs.\n"
        "//     One C entry per sibling *.dc.html except page.dc.html, sorted by\n"
        "//     filename, key \"./\"+filename, value the file's full source as a\n"
        "//     JSON string (2-space indent, non-ASCII kept literal). Do not rename\n"
        "//     the window.__resourceBlobs global — support.js reads it; a different\n"
        "//     name or shape silently no-ops. Full procedure: .claude/CLAUDE.md.\n"
        "(function () {\n"
        "  var C = " + body + ";\n"
        "  window.__resourceBlobs = window.__resourceBlobs || {};\n"
        "  for (var k in C) {\n"
        "    if (!window.__resourceBlobs[k]) {\n"
        "      window.__resourceBlobs[k] = new Blob([C[k]], { type: \"text/html\" });\n"
        "    }\n"
        "  }\n"
        "})();\n",
        encoding="utf-8",
    )
    names = ", ".join(p.name for p in COMPONENTS)
    print(f"components.js: bundled {len(COMPONENTS)} component(s) — {names}")


if __name__ == "__main__":
    sys.exit(main())
